### ISSUE TITLE
Publish to F-Droid

### ISSUE THREAD

**Issue by uniqx** [stefanmedack/cccTV#30]
It would be really great if you could publish this App to F-Droid.
https://gitlab.com/fdroid/rfp/issues/new?issue

**Comment by stefanmedack** [comment]
I'd love to, but last time I checked there was no TV support on F-Droid.

However, you can sideload the APKs to your TV directly, if you do not want to use the stores. You can find every release in the [Github Releases](https://github.com/stefanmedack/cccTV/releases)
