### ISSUE TITLE
🚨 Use a specific user agent for media.ccc.de 🚨

### ISSUE THREAD

**Issue by manno** [stefanmedack/cccTV#32]
Hi,

Requests from 'okhttp' to the public JSON API of media.ccc.de make up 98% of the total traffic now and it's affecting performance.
Maybe some of those requests can be avoided,  seems odd that we output several 100gb of JSON each day. However I'm not sure where those requests are coming from.

As first countermeasure I want to rate limit the 'okhttp' user agent. If I understand correctly cccTV currently uses that agent? Can you set an app specific agent, so we can tell the apps apart?

**Comment by stefanmedack** [comment]
Hi Mario,

okHttp is a very common library for http requests on Android/Java/Kotlin. So I am pretty sure that it is the sum of all mobile clients that raise the traffic.

In this project I use https://github.com/johnjohndoe/c3media-base to access the media.ccc.de which is probably used in other projects as well. 
And than there is also https://github.com/NiciDieNase/chaosflix that most likely uses okHttp.

Honestly speaking, I am not very active on this project anymore. Most things I did here are also available in Chaosflix by now + Chaosflix is also available for phone/tablet.

**Comment by manno** [comment]
Hey @stefanmedack 

Very well, Chaosflix did already [react](https://github.com/NiciDieNase/chaosflix/issues/39) and that should be enough to debug this issue.

**Comment by johnjohndoe** [comment]
FYI: @manno I updated the underlying library.
