### ISSUE TITLE
Sreensaver (Backdrop) on running Stream

### ISSUE THREAD

**Issue by Hellmudth** [stefanmedack/cccTV#7]
Screensaver will overlay the Video/Stream. On Livestreams the audio will continue in the background, but Screen turns to Android TV Screensaver (in my case Backdrop), Videos from the Mediathek are paused, on Nvidia ShieldTV. Version 2.0.0-RC4_TV

**Comment by stefanmedack** [comment]
Thx for the feedback. I had the problem myself and just fixed it in RC5 ;)
